# -*- coding: utf-8 -*-
"""coursera_foundation_module_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f9ttfUJ6gLNi0aILO9AMt6hghhsQdNkM

# Analyze Product Sentiment
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

"""# Read product review data"""

file_data = '/content/drive/MyDrive/Colab Notebooks/Coursera_Foundation/Module 3/amazon_baby.csv'
products = pd.read_csv(file_data)

"""# Explore data"""

products

products.groupby('name',operations={'count':turicreate.aggregate.COUNT()}).sort('count',ascending=False)

"""# Examine the reivews for the most-reviewed product"""

giraffe_reviews = products[products['name']=='Vulli Sophie the Giraffe Teether']

giraffe_reviews

len(giraffe_reviews)

giraffe_reviews['rating'].show()

"""# Building a sentiment classifier

## Build word count vectors
"""

products['word_count'] = turicreate.text_analytics.count_words(products['review'])

products

"""# Define what is positive and negative sentiment"""

products['rating'].show()

#ignore all 3*  reviews
products = products[products['rating']!= 3]

#positive sentiment = 4-star or 5-star reviews
products['sentiment'] = products['rating'] >= 4

products

products['sentiment'].show()

"""# Train our sentiment classifier"""

train_data,test_data = products.random_split(.8,seed=0)

sentiment_model = turicreate.logistic_classifier.create(train_data,target='sentiment', features=['word_count'], validation_set=test_data)

"""# Apply the sentiment classifier to better understand the Giraffe reviews"""

products['predicted_sentiment'] = sentiment_model.predict(products, output_type = 'probability')

products

giraffe_reviews = products[products['name']== 'Vulli Sophie the Giraffe Teether']

giraffe_reviews

"""# Sort the Giraffe reviews according to predicted sentiment"""

giraffe_reviews = giraffe_reviews.sort('predicted_sentiment', ascending=False)

giraffe_reviews

giraffe_reviews.tail()

"""## Show the most positive reviews"""

giraffe_reviews[0]['review']

giraffe_reviews[1]['review']

"""# Most negative reivews"""

giraffe_reviews[-1]['review']

giraffe_reviews[-2]['review']